apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: prakhar1989/static-site
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
spec:
  type: LoadBalancer
  loadBalancerIP: 52.249.241.73
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80